# Generated by Django 3.2.7 on 2021-09-20 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_aboutbackgroundimage_contactbackgroundimage_indexbackgroundimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogdetail',
            name='blog_location',
        ),
    ]
