# Generated by Django 3.2.7 on 2021-09-20 17:38

import blogs.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_remove_blogdetail_blog_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutbackgroundimage',
            name='bg_image_1',
            field=models.FileField(blank=True, default='', upload_to='background/about/', validators=[blogs.validators.validate_image_extension]),
        ),
        migrations.AddField(
            model_name='aboutbackgroundimage',
            name='desc1',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='aboutbackgroundimage',
            name='desc2',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='aboutbackgroundimage',
            name='personal_image_about',
            field=models.FileField(blank=True, default='', upload_to='background/about/', validators=[blogs.validators.validate_image_extension]),
        ),
        migrations.AddField(
            model_name='aboutbackgroundimage',
            name='text_quotations',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
