# Generated by Django 3.2.7 on 2021-09-20 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20210920_2038'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutBackgroundImage',
            new_name='About',
        ),
    ]
