# Generated by Django 3.2.7 on 2021-09-20 19:56

import blogs.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_rename_aboutbackgroundimage_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_image', models.FileField(blank=True, upload_to='background/index/', validators=[blogs.validators.validate_image_extension])),
                ('slide_title', models.CharField(blank=True, default='', max_length=300)),
                ('slide_sub_title', models.CharField(blank=True, default='', max_length=300)),
                ('slide_text', models.CharField(blank=True, default='', max_length=300)),
                ('slide_facebook', models.CharField(blank=True, default='', max_length=300)),
                ('slide_twitter', models.CharField(blank=True, default='', max_length=300)),
                ('slide_instagram', models.CharField(blank=True, default='', max_length=300)),
                ('slide_linkedIn', models.CharField(blank=True, default='', max_length=300)),
            ],
        ),
    ]
