# Generated by Django 3.2.7 on 2021-09-20 20:20

import blogs.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instagram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insta_facebook1', models.FileField(blank=True, upload_to='background/index/', validators=[blogs.validators.validate_image_extension])),
                ('insta_facebook2', models.FileField(blank=True, upload_to='background/index/', validators=[blogs.validators.validate_image_extension])),
                ('insta_facebook3', models.FileField(blank=True, upload_to='background/index/', validators=[blogs.validators.validate_image_extension])),
                ('insta_facebook4', models.FileField(blank=True, upload_to='background/index/', validators=[blogs.validators.validate_image_extension])),
                ('insta_facebook5', models.FileField(blank=True, upload_to='background/index/', validators=[blogs.validators.validate_image_extension])),
                ('insta_facebook6', models.FileField(blank=True, upload_to='background/index/', validators=[blogs.validators.validate_image_extension])),
                ('insta_desc', models.CharField(blank=True, default='', max_length=300)),
                ('insta_hash', models.CharField(blank=True, default='', max_length=300)),
            ],
        ),
    ]
