# Generated by Django 3.2.7 on 2021-09-20 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_instagram'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactBackgroundImage',
        ),
    ]
