# Generated by Django 3.2.7 on 2021-10-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_auto_20211002_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetail',
            name='blog_title_1',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='blogdetail',
            name='blog_title_1_desc1',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='blogdetail',
            name='blog_title_1_desc2',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='blogdetail',
            name='blog_title_1_desc3',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='blogdetail',
            name='blog_title_1_desc4',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='blogdetail',
            name='blog_title_2',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='blogdetail',
            name='blog_title_2_desc1',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='blogdetail',
            name='blog_title_2_desc2',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='blogdetail',
            name='blog_title_2_desc3',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='blogdetail',
            name='blog_title_2_desc4',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
