# Generated by Django 3.2.7 on 2021-10-02 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_auto_20211002_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetail',
            name='blog_title_1',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='blogdetail',
            name='blog_title_2',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
