# Generated by Django 3.2.7 on 2021-10-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_auto_20211002_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogdetail',
            name='blog_title_1_desc2',
        ),
        migrations.RemoveField(
            model_name='blogdetail',
            name='blog_title_1_desc3',
        ),
        migrations.RemoveField(
            model_name='blogdetail',
            name='blog_title_1_desc4',
        ),
        migrations.RemoveField(
            model_name='blogdetail',
            name='blog_title_2_desc2',
        ),
        migrations.RemoveField(
            model_name='blogdetail',
            name='blog_title_2_desc3',
        ),
        migrations.RemoveField(
            model_name='blogdetail',
            name='blog_title_2_desc4',
        ),
        migrations.AddField(
            model_name='blogdetail',
            name='blog_title_3',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='blogdetail',
            name='blog_title_3_desc1',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='blogdetail',
            name='blog_title_4',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='blogdetail',
            name='blog_title_4_desc1',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='blogdetail',
            name='blog_title_5',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='blogdetail',
            name='blog_title_5_desc1',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
