# Generated by Django 3.2.7 on 2021-10-02 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_auto_20211002_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetail',
            name='blog_desc_insatll_1',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='blogdetail',
            name='blog_desc_insatll_2',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='blogdetail',
            name='blog_desc_insatll_3',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
