# Generated by Django 3.2.7 on 2021-10-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0013_auto_20211002_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetail',
            name='blggggog_title_4_desc1',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='blogdetail',
            name='ggblog_title_4',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
