# Generated by Django 3.2.7 on 2021-10-04 12:19

import blogs.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0014_auto_20211002_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogdetail',
            name='blggggog_title_4_desc1',
        ),
        migrations.RemoveField(
            model_name='blogdetail',
            name='ggblog_title_4',
        ),
        migrations.AddField(
            model_name='blogdetail',
            name='blog_image_blog_title_1desc_1',
            field=models.FileField(blank=True, default='', upload_to='background/stories_detail/', validators=[blogs.validators.validate_image_extension]),
        ),
    ]
