# Generated by Django 3.2.7 on 2021-10-04 14:10

import blogs.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0015_auto_20211004_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetail',
            name='blog_image_blog_title_2_desc1',
            field=models.FileField(blank=True, default='', upload_to='background/stories_detail/', validators=[blogs.validators.validate_image_extension]),
        ),
        migrations.AddField(
            model_name='blogdetail',
            name='blog_image_blog_title_3_desc1',
            field=models.FileField(blank=True, default='', upload_to='background/stories_detail/', validators=[blogs.validators.validate_image_extension]),
        ),
        migrations.AddField(
            model_name='blogdetail',
            name='blog_image_blog_title_4_desc1',
            field=models.FileField(blank=True, default='', upload_to='background/stories_detail/', validators=[blogs.validators.validate_image_extension]),
        ),
        migrations.AddField(
            model_name='blogdetail',
            name='blog_image_blog_title_5_desc1',
            field=models.FileField(blank=True, default='', upload_to='background/stories_detail/', validators=[blogs.validators.validate_image_extension]),
        ),
    ]
