# Generated by Django 3.2.7 on 2021-10-04 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0016_auto_20211004_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogdetail',
            name='blog_desc_insatll_2',
        ),
    ]
