# Generated by Django 3.2.7 on 2021-10-04 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0017_remove_blogdetail_blog_desc_insatll_2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogdetail',
            old_name='blog_desc_insatll_3',
            new_name='blog_desc_insatll_package_3',
        ),
    ]
