# Generated by Django 3.2.7 on 2021-10-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0019_auto_20211004_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogdetail',
            name='blog_desc_insatll_package_6',
        ),
        migrations.AddField(
            model_name='blogdetail',
            name='blog_title_1_desc2',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
    ]
