# Generated by Django 3.2.7 on 2021-10-04 17:31

import blogs.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0021_auto_20211004_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetail',
            name='blog_image2_blog_title_4_desc1',
            field=models.FileField(blank=True, default='', upload_to='background/stories_detail/', validators=[blogs.validators.validate_image_extension]),
        ),
        migrations.AddField(
            model_name='blogdetail',
            name='blog_title_4_desc2',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
