# Generated by Django 3.2.7 on 2021-10-04 17:49

import blogs.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0023_blogdetail_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetail',
            name='note_image',
            field=models.FileField(blank=True, default='', upload_to='background/stories_detail/', validators=[blogs.validators.validate_image_extension]),
        ),
    ]
