# Generated by Django 3.2.7 on 2021-10-04 17:52

import blogs.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0024_blogdetail_note_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetail',
            name='note1',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='blogdetail',
            name='note_image_1',
            field=models.FileField(blank=True, default='', upload_to='background/stories_detail/', validators=[blogs.validators.validate_image_extension]),
        ),
    ]
