# Generated by Django 3.2.7 on 2021-10-04 18:06

import blogs.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0025_auto_20211004_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetail',
            name='blog_desc4_image_1',
            field=models.FileField(blank=True, default='', upload_to='background/stories_detail/', validators=[blogs.validators.validate_image_extension]),
        ),
        migrations.AddField(
            model_name='blogdetail',
            name='thanks',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
