# Generated by Django 3.2.7 on 2021-10-04 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0026_auto_20211004_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogdetail',
            name='thanks',
        ),
    ]
