# Generated by Django 3.2.7 on 2021-10-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0027_remove_blogdetail_thanks'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetail',
            name='blog_resourse1',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='blogdetail',
            name='blog_resourse2',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='blogdetail',
            name='blog_resourse3',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='blogdetail',
            name='blog_resourse4',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='blogdetail',
            name='blog_resourse5',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
